### ISSUE TITLE
install via pip not correct? 

### ISSUE THREAD

**Issue by DocMinus** [Arch4ngel21/scikit-fingerprints#64]
Hi, 
an interesting approach you have here. but I am having some issues:
To install I had to use "poetry install". the pip install from the readme didn't work (not unexpected perhaps; and using the local folder wouldn't work with pip since there isn't a setup.py), so I am not sure what you are referring to.

I see also you use tqdm, common, but in the sense of acceleration one should note that tqdm itself can slow down processes substantially. You might want to try with several hundreds of k sized dataset and you will notice the difference with and without tqdm (at the price of not seeing progress of course).

what is interesting - side note - is that there is not substantial increase in py3.11 vs 3.9; 3.11 is usual 2-6 times faster for most things. meaning you probably have good optimization ongoing?

**Comment by j-adamczyk** [comment]
@DocMinus thanks for interest in our library!

This is being written as a part of engineering thesis which I'm co-supervising, and we need to finish writing it right now. However, we'll get right into upgrading the library once we finish it in about two or three weeks.

In terms of installation, I was able to install it as `pip install scikit-fingerprints` without any problem on fresh Python 3.11 venv, and also use it. But we'll verify other Python versions, and also update README to point to new name. We also need to refactor dependencies, in particular remove OGB and all benchmark-related stuff from the library itself.

You're absolutely right about tqdm, we'll change it to depend on `verbose` argument.

About Python 3.11, we mostly rely on RDKit for actual computation of fingerprints, so the Python layer is quite efficient. Purely Python-based fingerprints, like MAP4, are quite slow though. This is both due to how they work, and because Python itself is slow. We may need to rewrite it in Cython at some point.

**Comment by DocMinus** [comment]
Thank you. And good luck with the thesis. I will close this issue then.
